<div class="relogio">
    <div class="horas sub-relogio">
        <span class="horas-values top" id="hour">00</span>
        <span class="horas-name bottom">Horas</span>
    </div>

    <div class="minutos sub-relogio">
        <span class="minutos-value top" id="minute">00</span>
        <span class="minutos-name bottom">minutos</span>
    </div>

    <div class="segundos sub-relogio change">
        <span class="segundos-value top" id="second">00</span>
        <span class="segundos-name bottom">segundos</span>
    </div>
</div>
<div class="data"></div>