<script src="/script/changeFile.js" defer></script>

<div class="container mt-5">
    <h2 class="text-center">Formulário de Cadastro</h2>
    <form class="form-row">
        <div class="form-group col-sm-6 my-4">
            <label for="nome" class="col-form-label">Nome</label>
            <div class="col-sm-6">
                <input type="text" class="form-control" id="nome" required>
            </div>
            <label for="email" class="col-form-label">E-mail</label>
            <div class="col-sm-6">
                <input type="email" class="form-control" id="email" required>
            </div>
        </div>
        <div class="form-group col-sm-6 my-4">
            <label for="senha" class="col-form-label">Senha</label>
            <div class="col-sm-6">
                <input type="password" class="form-control" id="senha" required>
            </div>
            <label for="pin" class="col-form-label">PIN</label>
            <div class="col-sm-6">
                <input type="password" class="form-control" id="pin" required>
            </div>
        </div>
        <div class="form-group col-sm-6 my-4">
            <label for="nascimento">Data de Nascimento</label>
            <div class="col-sm-6">
                <input type="date" class="form-control" id="nascimento" required>
            </div>
            <label for="telefone">Telefone</label>
            <div class="col-sm-6">
                <input type="tel" class="form-control" id="phoneInput" required>
            </div>
        </div>
        <div class="form-group col-sm-6 my-4">
            <label for="permissao">Permissão</label>
            <div class="col-sm-6">
                <select class="form-control" id="permissao" required>
                    <option value="">Selecione uma opção</option>
                    <option value="admin">Admin</option>
                    <option value="usuario">Usuário</option>
                </select>
            </div>
            <label for="foto">Foto de Perfil</label>
            <div class="col-sm-6">
                <input type="file" class="form-control-file" id="customFile" required>
            </div>
        </div>
        <div class="form-group col-sm-8 offset-col-sm-2 my-5">
            <label for="empregador" class="text-center">Código do Empregador</label>
            <input type="text" class="form-control" readonly id="empregador" value="#####" style="background-color: black;color: white;"required>
        </div>

        <div class="form-group col-sm-8 offset-col-sm-2">
            <button type="submit" class="btn btn-primary w-100">Cadastrar</button>
        </div>

    </form>
    <img src="" id="preview" style="border-radius: 100%;display: block;position: absolute;top: 22rem;right: 14rem;width: 100px;height: 100px;">
</div>