<html>
  <head>
    <script>
      
    </script>
  </head>
  <body>
    <div id="filterContainerSession">
      <input type="checkbox" class="filterSession" value="Manhã" onclick="filterTable()" checked>Manhã
      <input type="checkbox" class="filterSession" value="Tarde" onclick="filterTable()" checked>Tarde
      <input type="checkbox" class="filterSession" value="Noite" onclick="filterTable()" checked>Noite
    </div>
    <br>
    <div id="filterContainerRole">
      <input type="checkbox" class="filterRole" value="Gerente" onclick="filterTable()" checked>Gerente
      <input type="checkbox" class="filterRole" value="Assistente" onclick="filterTable()" checked>Assistente
      <input type="checkbox" class="filterRole" value="Estágiario" onclick="filterTable()" checked>Estágiario
    </div>
    <br><br>
    <table id="employeeTable">
      <tr>
        <th>Nome</th>
        <th>Sessão</th>
        <th>Cargo</th>
      </tr>
      <tr>
        <td>João Silva</td>
        <td>Manhã</td>
        <td>Gerente</td>
      </tr>
      <tr>
        <td>Maria Santos</td>
        <td>Tarde</td>
        <td>Assistente</td>
      </tr>
      <tr>
        <td>Lucas Oliveira</td>
        <td>Manhã</td>
        <td>Gerente</td>
      </tr>
      <tr>
        <td>Ana Rodrigues</td>
        <td>Tarde</td>
        <td>Assistente</td>
      </tr>
      <tr>
        <td>Ana Rodrigues</td>
        <td>Noite</td>
        <td>Estágiario</td>
      </tr>
      
    </table>
  </body>
</html>

