<?php

    $images = scandir("img");
    $allData = array();

    foreach ($images as $img) {
        if(!in_array($img, array(".",".."))){
            $filename = 'img/'. $img;
            $file = pathinfo($filename);
            $file['size'] = filesize($filename);
            $file['modified'] = date('d/m/y H:i:s', filemtime($filename));
            // $file['url'] = "http://localhost:8080/".$filename; 
            // echo "<pre>";
            // var_dump($file);
            // echo "</pre> <br> <br>";

            if(!is_dir("../vendor/MF/log")){
                mkdir("../vendor/MF/log");
            }

            array_push($allData, $file);

        }
    }
   
    $fileOpen = fopen("../vendor/MF/log/log.txt", "a+");
    fwrite($fileOpen, "Usuario :". $_SESSION['nome']. " Acessou o Sistema às ". date('H:i:s'). " Do dia ". date('d/m/Y'). "\n");
    fclose($fileOpen);

    