<?php
    $headers = array();
    $allData = array();

    foreach ($allData[0] as $key => $value) {
        array_push($headers,ucfirst($key));
    }

    $newFile = fopen("../vendor/MF/log/data.csv", "w+");
    fwrite($newFile, "| ".implode(' | ', $headers). " |\n");
    
    foreach ($allData as $row) {
        $data = array();

        foreach ($row as $value) {
            array_push($data, $value);
        }
        fwrite($newFile, "| ".implode(' | ', $data). " |\n");
    }
    fclose($newFile);