<section class="flex flex-col items-center justify-center w-screen h-screen">
    <div class="w-80 mb-2 border-b-1 border-white">
        <ul class="flex text-center p-0 mb-0 w-full">
            <li class="active p-3 border-b-2 border-black active:bg-lime-400 hover:bg-lime-300 cursor-pointer w-full rounded-t-md rounded-l-md active:border-b-green-500" onclick="loginOption(0)" id="func">Empregador</li>
            <li class="p-3 border-b-2 border-black active:bg-lime-400 hover:bg-lime-300 cursor-pointer w-full rounded-t-md rounded-r-md active:border-b-green-500" onclick="loginOption(1)" id="client">Colaborador</li>
        </ul>
    </div>
    <div class="bg-black w-80">
        <!-- /.login-logo -->

        <div class="max-w-[500px] bg-white rounded mt-1">
            <!-- 
            <div class="card-body fade show" id="cardFunc">
                <div class="card-header text-center mb-3">
                    <a href="/" class="h1">Empregador</a>
                </div>
                <p class="login-box-msg">Insira seus dados para iniciar Sessão</p>

                <form action="/auth/empregador/login" method="post">
                    <div class="input-group mb-3">
                        <input type="text" class="form-control" name="employerEmail" placeholder="Insira seu email de Empregador">
                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fa-solid fa-user"></span>
                            </div>
                        </div>
                    </div>
                    <div class="input-group mb-3">
                        <input type="password" class="form-control" name="employerPassword" placeholder="Insira senha da conta">
                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-lock"></span>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-4">
                            <button type="submit" class="btn btn-primary btn-block">Entrar</button>
                        </div>
                    </div>
                </form>
            </div>
-->
            <div class="card-body fad show" id="cardClient">
                <div class="card-header text-center mb-3">
                    <a href="/" class="h1">Colaborador</a>
                </div>
                <form action="/auth/empregado/login" method="post">
                    <div class="input-group mb-3">
                        <input type="text" class="form-control" name="codEmployer" placeholder="Insira o Código do Empregador">
                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fa-solid fa-bell"></span>
                            </div>
                        </div>
                    </div>
                    <div class="input-group mb-3">
                        <input type="password" class="form-control" name="pinEmployer" placeholder="Insira o seu PIN">
                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-lock"></span>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-4">
                            <button type="submit" class="btn btn-primary btn-block">Entrar</button>
                        </div>
                    </div>
                </form>
            </div>


        </div>
    </div>
</section>

<script>
</script>