<!DOCTYPE html>
<html lang="pt-br">

<head>

	<?php $this->loadComponent('metaTags'); ?>
	<?php $this->loadComponent('CDNs'); ?>
	<?php $this->loadComponent('favico'); ?>
	<link rel="stylesheet" href="/css/auth.css">

	<!-- TITTLE -->
	<title>Sessão de Acesso | Entre com usuario |</title>
</head>

<body>

	<?php $this->content() ?>
	<?php $this->loadComponent('toast')?>

	
</body>
<script src="/script/changeMenu.js">

</script>
</html>