<!DOCTYPE html>
<html lang="pt-br">

<head>
	<?php $this->loadComponent('metaTags'); ?>
	<?php $this->loadComponent('jqueryAwesome'); ?>
	<?php $this->loadComponent('favico'); ?>

	<link rel="stylesheet" href="/css/relogio.css">
	<link rel="stylesheet" href="/css/baterPonto.css">
	<link rel="stylesheet" href="/css/navbar.css">
	
	<title>Ponto Digital | Registro De Ponto |</title>
</head>

<body>

	<?php $this->loadComponent('toast')?>
	<main id="admin">
		<?php $this->loadComponent('navbar')?>
		<div class="content">
			<?php $this->content() ?>
		</div>
	</main>
	

</body>
<script src="/script/relogio.js"></script>
<script src="/script/getDate.js"></script>
<script src="/script/baterPonto.js"></script>

</html>