<!DOCTYPE html>
<html lang="pt-br">
<head>
	<?php $this->loadComponent('metaTags'); ?>
	<?php $this->loadComponent('favico'); ?>
	<?php $this->loadComponent('CDNs'); ?>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
	<style>
      .form-group {
        width: 50%;
        margin: 0 auto;
	}
	</style>
	<title>Amizade</title>
</head>
<body>
	<?php $this->content() ?>
</body>
</html>