<section class="accessContainer">
    <div style="width: 360px;">
        <ul class="login-option d-flex align-center p-0 mb-0 justify-content-between">
            <li class="active p-3" onclick="loginOption(0)" id="func">Empregador</li>
            <li class="p-3" onclick="loginOption(1)" id="client">Colaborador</li>
        </ul>
    </div>
    <div class="login-box">
        <!-- /.login-logo -->
        <div class="card card-outline card-primary">

            <div class="card-body fade show" id="cardFunc">
                <div class="card-header text-center mb-3">
                    <a href="/" class="h1">Empregador</a>
                </div>
                <p class="login-box-msg">Insira seus dados para iniciar Sessão</p>

                <form action="/auth/empregador/login" method="post">
                    <div class="input-group mb-3">
                        <input type="text" class="form-control" name="employerEmail" placeholder="Insira seu email de Empregador">
                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fa-solid fa-user"></span>
                            </div>
                        </div>
                    </div>
                    <div class="input-group mb-3">
                        <input type="password" class="form-control" name="employerPassword" placeholder="Insira senha da conta">
                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-lock"></span>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-4">
                            <button type="submit" class="btn btn-primary btn-block">Entrar</button>
                        </div>
                    </div>
                </form>
            </div>

            <div class="card-body fade" id="cardClient">
                <div class="card-header text-center mb-3">
                    <a href="/" class="h1">Colaborador</a>
                </div>
                <form action="/auth/empregado/login" method="post">
                    <div class="input-group mb-3">
                        <input type="text" class="form-control" name="codEmployer" placeholder="Insira o Código do Empregador">
                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fa-solid fa-bell"></span>
                            </div>
                        </div>
                    </div>
                    <div class="input-group mb-3">
                        <input type="password" class="form-control" name="pinEmployer" placeholder="Insira o seu PIN">
                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-lock"></span>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-4">
                            <button type="submit" class="btn btn-primary btn-block">Entrar</button>
                        </div>
                    </div>
                </form>
            </div>


        </div>
    </div>
</section>

<script>
</script>