<nav class="sidebar">
    <ul>
        <a href="#">
            <li>Home <i class="fa fa-trash"></i></li>
        </a>
        <a href="#">
            <li>Relatorio de pontos<i class="fa fa-trash"></i></li>
        </a>
        <a href="/registrarPonto">
            <li>Registrar Ponto<i class="fa fa-trash"></i></li>
        </a>
    </ul>
    <a href="/logout">
        <div id="sair">Sair</div>
    </a>
</nav>