<div id="filters">

    <h3>Filtros</h3>
    <div class="filter-group">
        <h4>Sessão</h4>
        <div class="filter-item">
            <input type="checkbox" id="CozinhaA1" value="session-CozinhaA1">
            <label for="CozinhaA1">CozinhaA1</label>
        </div>
        <div class="filter-item">
            <input type="checkbox" id="Sistemas-e-Hardware" value="session-Sistemas-e-Hardware">
            <label for="Sistemas-e-Hardware">Sistemas e Hardware</label>
        </div>
        <div class="filter-item">
            <input type="checkbox" id="Administração" value="session-Administração">
            <label for="Administração">Administração</label>
        </div>
    </div>

    <div class="filter-group">
        <h4>Cargo</h4>
        <div class="filter-item">
            <input type="checkbox" id="estagiario" value="cargo-estagiario">
            <label for="estagiario">estagiario</label>
        </div>
        <div class="filter-item">
            <input type="checkbox" id="Funcionario" value="cargo-Funcionario">
            <label for="Funcionario">Funcionario</label>
        </div>
        <div class="filter-item">
            <input type="checkbox" id="Admininstrador" value="cargo-Admininstrador">
            <label for="Admininstrador">Admininstrador</label>
        </div>
        <div class="filter-item">
            <input type="checkbox" id="Gestor" value="cargo-Gestor">
            <label for="Gestor">Gestor</label>
        </div>
        <div class="filter-item">
            <input type="checkbox" id="Chamada" value="cargo-Chamada">
            <label for="Chamada">Chamada</label>
        </div>
        <div class="filter-item">
            <input type="checkbox" id="Chefe-da-Sessao" value="cargo-Chefe-da-Sessao">
            <label for="Chefe-da-Sessao">Chefe da Sessao</label>
        </div>
    </div>

    <div class="filter-group">
        <h4>Config</h4>
        <div class="filter-item">
            <input type="checkbox" id="ativo" value="config-ativo">
            <label for="ativo">Ativo</label>
        </div>
        <div class="filter-item">
            <input type="checkbox" id="pontoRegistrado" value="config-pontoRegistrado">
            <label for="pontoRegistrado">Registrou Ponto Hoje</label>
        </div>

    </div>
    <button id="apply-filters">Aplicar Filtros</button>
</div>