<div id="filters">
    <span class="closeMenu" onclick="openMenu()">
        <i class="fa-solid fa-xmark"></i>
    </span>
    <h3>Filtros</h3>
    <div class="filter-group">
        <h4>Sessão</h4>
        <div class="filter-item">
            <input type="checkbox" class="filterSession" id="CozinhaA1" value="CozinhaA1" onclick="filterTable()">
            <label for="CozinhaA1">CozinhaA1</label>
        </div>
        <div class="filter-item">
            <input type="checkbox" class="filterSession" id="Sistemas-e-Hardware" value="Sistemas-e-Hardware"  onclick="filterTable()">
            <label for="Sistemas-e-Hardware">Sistemas e Hardware</label>
        </div>
        <div class="filter-item">
            <input type="checkbox" class="filterSession" id="Administração" value="Administração" onclick="filterTable()">
            <label for="Administração">Administração</label>
        </div>
    </div>

    <div class="filter-group">
        <h4>Cargo</h4>
        <div class="filter-item">
            <input type="checkbox" class="filterRole" onclick="filterTable()" id="estagiario" value="estagiario">
            <label for="estagiario">estagiario</label>
        </div>
        <div class="filter-item">
            <input type="checkbox" class="filterRole" onclick="filterTable()" id="Funcionario" value="Funcionario">
            <label for="Funcionario">Funcionario</label>
        </div>
        <div class="filter-item">
            <input type="checkbox" class="filterRole" onclick="filterTable()" id="Admininstrador" value="Admininstrador">
            <label for="Admininstrador">Admininstrador</label>
        </div>
        <div class="filter-item">
            <input type="checkbox" class="filterRole" onclick="filterTable()" id="Gestor" value="Gestor">
            <label for="Gestor">Gestor</label>
        </div>
        <div class="filter-item">
            <input type="checkbox" class="filterRole" onclick="filterTable()" id="Chamada" value="Chamada">
            <label for="Chamada">Chamada</label>
        </div>
        <div class="filter-item">
            <input type="checkbox" class="filterRole" onclick="filterTable()" id="Chefe-da-Sessao" value="Chefe-da-Sessao">
            <label for="Chefe-da-Sessao">Chefe da Sessao</label>
        </div>
    </div>
</div>