<nav>
    <ul class="functions">
        <li><i class="fa-solid fa-user-pen" style="color: blue;"></i>Editar</li>
        <li><i class="fa-solid fa-user-check" style="color: green;"></i>Ativar</li>
        <li><i class="fa-solid fa-user-lock" style="color: black;"></i>Bloquear</li>
        <li><i class="fa-solid fa-user-xmark" style="color:red ;"></i>Excluir</li>
        <li><i class="fa-solid fa-user-shield" style="color: rebeccapurple;"></i>Restaurar</li>
    </ul>
</nav>